### PR TITLE
fix predictions write to file

### PR DESCRIPTION
**Pull request by PanayotisManganaris**
this is dependent on changes made to the dataloader in the jarvis.core.graphs module.

### CODE REVIEW

**Comment by PanayotisManganaris** [comment]
the associated dataloader changes https://github.com/usnistgov/jarvis/pull/261

**Comment by knc6** [comment]
Hi @PanayotisManganaris Thanks for the PR. It seems some of the tests are still failing: https://github.com/usnistgov/alignn/actions/runs/3449913547/jobs/5760433618#step:6:405

**Comment by PanayotisManganaris** [comment]
Thanks for taking a look, Kamal. I did notice but I'm not sure why. I tried running the tests myself but I encountered an error when invoking pytest, both plainly and through coverage. I will try reconstructing my environment from my forks and make any necessary commits, but I can't give an ETA just now.

I'll ask concrete questions if they come up.

**Comment by PanayotisManganaris** [comment]
I'm going to start over with this one

**Pull request closed without merging**
